from main import classify

## Tests
print("--- negativity ---")
print("bad", classify("bad, you did badly"))
print("bad in Lithuanian", classify("blogai, blogai padarei"))
print("poor", classify("you did poorly"))
print("terrible day", classify("this has been a terrible day"))
print("terrible in French", classify("c'est vraiment terrible, quelle horreur"))
print("bad in Japanese", classify("最悪だ、本当にひどい"))
print("awful in German", classify("das war schrecklich, einfach furchtbar"))

print("--- positivity ---")
print("good", classify("good, good job!"))
print("well", classify("you did well"))
print("beautiful day", classify("what a beautiful day it is"))
print("happy in Spanish", classify("estoy muy feliz, que dia tan bonito"))
print("joy in Korean", classify("너무 행복해요, 오늘 정말 좋은 날이에요"))
print("wonderful in Italian", classify("che bella giornata, sono contentissimo"))

print("--- praises ---")
print("excellent work", classify("excellent work on this project"))
print("proud of you", classify("I am so proud of you"))
print("nailed it", classify("you absolutely nailed it"))
print("bravo in French", classify("bravo, travail magnifique"))
print("well done in Portuguese", classify("muito bem, excelente trabalho"))
print("great in Japanese", classify("素晴らしい仕事ですね、よくやった"))

print("--- bullying ---")
print("insult", classify("you are such an idiot"))
print("exclusion", classify("nobody wants you here, go away"))
print("mockery", classify("everyone laughs at you behind your back"))
print("insult in Spanish", classify("eres un completo idiota, nadie te quiere"))
print("mockery in French", classify("t'es qu'un nul, tout le monde se moque de toi"))
print("insult in German", classify("du bist so ein Idiot, niemand mag dich"))

print("--- sarcasm ---")
print("oh really", classify("oh really, what a shocker"))
print("sure thing", classify("yeah right, sure thing buddy"))
print("slow clap", classify("wow, slow clap for that brilliant idea"))
print("sarcasm in French", classify("oh bien sur, quelle surprise incroyable"))
print("sarcasm in Spanish", classify("si claro, como si eso fuera verdad"))
print("sarcasm in German", classify("ja klar, was fuer eine Ueberraschung"))

print("--- gratitude ---")
print("thank you", classify("thank you so much for your help"))
print("appreciate it", classify("I really appreciate everything you have done"))
print("thanks in Spanish", classify("muchas gracias por todo"))
print("thanks in French", classify("merci beaucoup pour tout, je vous suis reconnaissant"))
print("thanks in Japanese", classify("本当にありがとうございます、感謝しています"))
print("thanks in Portuguese", classify("muito obrigado por tudo que voce fez"))

print("--- encouragement ---")
print("you can do it", classify("you can do it, I believe in you!"))
print("keep going", classify("don't give up, keep pushing forward"))
print("team spirit", classify("let's go team, we've got this!"))
print("courage in French", classify("tu peux le faire, je crois en toi, courage"))
print("go for it in Spanish", classify("tu puedes, no te rindas, adelante"))
print("keep going in Japanese", classify("頑張って、あなたならできる"))

print("--- humor ---")
print("lol", classify("lol that was hilarious"))
print("joke", classify("why did the chicken cross the road"))
print("haha", classify("haha I can't stop laughing"))
print("funny in Spanish", classify("jajaja que gracioso, no puedo parar de reir"))
print("funny in French", classify("mdr trop drole, je suis mort de rire"))
print("funny in Korean", classify("ㅋㅋㅋ 너무 웃겨요, 배꼽 빠지겠어"))

print("--- frustration ---")
print("annoyed", classify("ugh this is so annoying, nothing works"))
print("fed up", classify("I am so fed up with this nonsense"))
print("why", classify("why does this keep happening to me"))
print("frustrated in Spanish", classify("estoy harto, nada funciona, que rabia"))
print("frustrated in French", classify("j'en ai marre, rien ne marche, c'est insupportable"))
print("frustrated in Japanese", classify("もうイライラする、何もうまくいかない"))

print("--- curiosity ---")
print("how", classify("how does this work exactly?"))
print("wonder", classify("I wonder what would happen if we tried that"))
print("explain", classify("can you explain this to me?"))
print("curious in Spanish", classify("como funciona esto exactamente?"))
print("curious in French", classify("comment ca marche? je voudrais comprendre"))
print("curious in Japanese", classify("これはどういう仕組みですか？教えてください"))

print("--- toxicity ---")
print("threat", classify("I will find you and hurt you"))
print("hate", classify("I hate everyone like you"))
print("slur", classify("you disgusting piece of garbage, die"))
print("threat in Spanish", classify("te voy a encontrar y te vas a arrepentir"))
print("hate in French", classify("je te deteste, tu merites de souffrir"))
print("threat in German", classify("ich werde dich finden und du wirst es bereuen"))

print("--- emoji ---")
print("emoji 🎉", classify("🎉"))
print("emoji 😞", classify("😞"))
print("emoji 😂", classify("😂😂😂"))
print("emoji ❤️", classify("❤️"))
print("emoji 🤔", classify("🤔"))

print("--- mixed signals ---")
print("sarcastic praise", classify("oh great job, really, what a genius move"))
print("backhanded compliment", classify("well you tried your best I guess"))
print("polite frustration", classify("with all due respect, this is unacceptable"))
print("encouraging criticism", classify("you made a mistake but I know you can fix it"))
